#!/bin/bash
set -eu

pid=$$
pidfile=/tmp/red-line.pid
config_file=$HOME/.redline
MESSAGE_TIMEOUT=1

if [ ! -f $config_file ]; then
    cat > $config_file << EOF
normal-sleep=60
warning-sleep=5
warning-percent=10
critical-percent=3
critical-action=shutdown
critical-countdown=15
EOF
fi

function cleanup {
    if [ -f $pidfile ]
    then
        rm $pidfile
    fi
    exit
}

function get_option {
    option=$1
    value=$(echo -e "$config_file_content" | grep $option | awk -F '=' '{print $2}' | tr -d [:blank:])
    echo $value
}

function read_options {
    config_file_content="$(cat $config_file)"
    action=$(get_option critical-action)
    countdown=$(get_option critical-countdown)
    warning=$(get_option warning-percent)
    critical=$(get_option critical-percent)
    normal_sleep=$(get_option normal-sleep)
    warning_sleep=$(get_option warning-sleep)
}

trap "cleanup" SIGINT SIGTERM

trap "read_options" SIGHUP

if [ -f $pidfile ]
then
    echo 'red-line seems to be running already'
    exit
fi
echo $pid > $pidfile

function get_battery_state {
    echo $(acpi | awk '{print $3}' | awk -F ',' '{print $1}')
}

discharging="Discharging"
full="Full"
suspend_command="systemctl suspend"
shutdown_command="systemctl poweroff"
unknown="Unknown"

function is_discharging {
    state=$(get_battery_state)
    if [[ "$state" == "$discharging" ]]
    then
        echo "true"
    else
        echo "false"
    fi
}

read_options

function _notify_progress {
    summary="$1"
    progress=$2
    urgency=$3
    notify-send -u $urgency -h int:value:$progress -t $MESSAGE_TIMEOUT "$1"
}

function info_notify_progress {
    _notify_progress "$1" $2 low
}

function warning_notify_progress {
    _notify_progress "$1" $2 normal
}

function critical_notify_progress {
    _notify_progress "$1" $2 critical
}

function _notify_message {
    summary="$1"
    message="$2"
    urgency=$3
    notify-send -u $urgency "$summary" "$message"
}

function info_notify_message {
    _notify_message "$1" "$2" info
}

function critical_notify_message {
    _notify_message "$1" "$2" critical
}

while true; do
    batt=$(acpi | egrep -o '[0-9]+%' | egrep -o '[0-9]+')
    if [[ "$(is_discharging)" == "true" && "$batt" -le "$warning" ]]; then
        warning_notify_progress "Battery Low" $batt
        if [[ "$batt" -le "$critical" ]]
        then
            case $action in
                suspend|shutdown)
                    for i in $(seq 0 $countdown)
                    do
                        critical_notify_message "Will $action in" "$(expr $countdown - $i)"
                        if [[ "$(is_discharging)" == "false" ]]; then
                            info_notify_message "Phew" "Started charging"
                            break
                        fi
                    done
                    if [[ "$(is_discharging)" == "true" ]]; then
                    case $action in
                        suspend)
                            eval $suspend_command
                            ;;
                        shutdown)
                            eval $shutdown_command
                            ;;
                    esac
                    fi
                    ;;
                *)
                    ;;
            esac
        fi
        sleep $warning_sleep
    else
        state=$(get_battery_state)
        case $state in
            $full)
                info_notify_message "Battery Full" "Adapter Away!"
                ;;
            $unknown)
                info_notify_message "Battery Charging Transition" "At $batt%"
                ;;
        esac
        sleep $normal_sleep
    fi
done
